import Head from 'next/head';
import styles from '../styles/Home.module.css'
import axios from 'axios';
import TasksList from '../components/TaskList';

export async function getServerSideProps() {
  const res = await axios.get('https://api.jsonbin.io/v3/b/6304b4b65c146d63ca7bd581', { 
    headers: { 
      "Content-Type":	"application/json",
      "X-Access-Key": "6304b5fda1610e63860b814f"
    }
  })

  const data = res.data

  return { 
    props: { data: { data } }, 
  }
}

const Home = (props) => {
  return (
    <section>
        <main className={styles.main}>

            <div>
                <h1>FT Onboarding Tasks</h1>
            </div>
            <div className={styles.container}>

            <Head>
                <title>Onboarding</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>        
            <TasksList data={props.data}/>
            </div>
      </main>
    </section>
  )
}

export default Home;